# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: passkit_sdk/core/a_rpc_templates.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
require 'google/protobuf/empty_pb'
require 'passkit_sdk/common/common_objects_pb'
require 'passkit_sdk/common/template_pb'
require 'passkit_sdk/common/proximity_pb'
require 'passkit_sdk/common/links_pb'
require 'passkit_sdk/common/pagination_pb'
require 'passkit_sdk/common/filter_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file('passkit_sdk/core/a_rpc_templates.proto', :syntax => :proto3) do
  end
end

module PasskitSdk
  module Io
  end
end
