# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: passkit_sdk/core/a_rpc_certificates.proto for package 'io'

require 'grpc'
require 'passkit_sdk/core/a_rpc_certificates_pb'

module PasskitSdk
  module Io
    module Certificates
      class Service
        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'io.Certificates'

        rpc :getCertificateSigningRequest, Google::Protobuf::Empty, CertificateSigningRequest
        rpc :addAppleCertificate, FileBytes, CertificateData
        rpc :updateAppleCertificate, FileBytes, CertificateData
        rpc :getAppleCertificateData, PassTypeIdentifier, CertificateData
        rpc :listAppleCertificatesDeprecated, Pagination, stream(CertificateData)
        rpc :listAppleCertificates, Filters, stream(CertificateData)
        rpc :countAppleCertificatesDeprecated, Pagination, Count
        rpc :countAppleCertificates, Filters, Count
        rpc :sendNFCSigningCredentials, NFCSigningCredentialsRequest, Google::Protobuf::Empty
      end

      Stub = Service.rpc_stub_class
    end
  end
end
