# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: passkit_sdk/core/a_rpc_others.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
require 'google/protobuf/empty_pb'
require 'passkit_sdk/common/common_objects_pb'
require 'passkit_sdk/common/distribution_pb'
require 'passkit_sdk/common/project_pb'
require 'passkit_sdk/common/message_pb'
require 'passkit_sdk/common/job_pb'
require 'passkit_sdk/common/pagination_pb'
require 'passkit_sdk/common/filter_pb'
require 'passkit_sdk/common/integration_pb'
require 'passkit_sdk/user/user_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file('passkit_sdk/core/a_rpc_others.proto', :syntax => :proto3) do
  end
end

module PasskitSdk
  module Io
  end
end
