# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: passkit_sdk/core/a_rpc_templates.proto for package 'io'

require 'grpc'
require 'passkit_sdk/core/a_rpc_templates_pb'

module PasskitSdk
  module Io
    module Templates
      class Service
        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'io.Templates'

        rpc :createTemplate, PassTemplate, Id
        rpc :updateTemplate, PassTemplate, PassTemplate
        rpc :getTemplate, Id, PassTemplateResponse
        rpc :getDefaultTemplate, DefaultTemplateRequest, PassTemplate
        rpc :copyTemplate, CopyObjectInput, Id
        rpc :deleteTemplate, Id, Google::Protobuf::Empty
        rpc :listTemplatesForUserDeprecated, Pagination, stream(PassTemplateResponse)
        rpc :listTemplatesForUser, Filters, stream(PassTemplateResponse)
        rpc :listTemplatesDeprecated, Pagination, stream(PassTemplateResponse)
        rpc :listTemplates, Filters, stream(PassTemplateResponse)
        rpc :countTemplatesDeprecated, Pagination, Count
        rpc :countTemplates, Filters, Count
        rpc :countTemplatesForUserDeprecated, Pagination, Count
        rpc :countTemplatesForUser, Filters, Count
        rpc :createLocation, GPSLocation, Id
        rpc :updateLocation, GPSLocation, GPSLocation
        rpc :getLocation, Id, GPSLocation
        rpc :listLocationsDeprecated, Pagination, stream(GPSLocation)
        rpc :listLocations, Filters, stream(GPSLocation)
        rpc :copyLocation, CopyObjectInput, Id
        rpc :deleteLocation, Id, Google::Protobuf::Empty
        rpc :countLocationsDeprecated, Pagination, Count
        rpc :countLocations, Filters, Count
        rpc :createBeacon, Beacon, Id
        rpc :updateBeacon, Beacon, Beacon
        rpc :getBeacon, Id, Beacon
        rpc :listBeaconsDeprecated, Pagination, stream(Beacon)
        rpc :listBeacons, Filters, stream(Beacon)
        rpc :copyBeacon, CopyObjectInput, Id
        rpc :deleteBeacon, Id, Google::Protobuf::Empty
        rpc :countBeaconsDeprecated, Pagination, Count
        rpc :countBeacons, Filters, Count
        rpc :createLink, Link, Id
        rpc :updateLink, Link, Link
        rpc :getLink, Id, Link
        rpc :listLinksDeprecated, Pagination, stream(Link)
        rpc :listLinks, Filters, stream(Link)
        rpc :copyLink, CopyObjectInput, Id
        rpc :deleteLink, Id, Google::Protobuf::Empty
        rpc :countLinksDeprecated, Pagination, Count
        rpc :countLinks, Filters, Count
      end

      Stub = Service.rpc_stub_class
    end
  end
end
