# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: passkit_sdk/common/pagination.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file('passkit_sdk/common/pagination.proto', :syntax => :proto3) do
    add_message 'io.Pagination' do
      optional :limit, :int32, 1
      optional :offset, :int32, 2
      repeated :filterField, :string, 3
      repeated :filterValue, :string, 4
      repeated :filterOperator, :string, 5
      optional :orderBy, :string, 6
      optional :orderAsc, :bool, 7
    end
    add_message 'io.Filter' do
      repeated :filterField, :string, 1
      repeated :filterValue, :string, 2
      repeated :filterOperator, :string, 3
    end
  end
end

module PasskitSdk
  module Io
    Pagination = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('io.Pagination').msgclass
    Filter = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('io.Filter').msgclass
  end
end
