# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: passkit_sdk/widget/widget.proto for package 'widget'

require 'grpc'
require 'passkit_sdk/widget/widget_pb'

module PasskitSdk
  module Widget
    class Service
      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'widget.widgetConfiguration'

      rpc :getWidgetConfiguration, WidgetKey, WidgetConfiguration
      rpc :resetConfiguration, WidgetKey, WidgetConfiguration
      rpc :updateIdentityVerification, UpdateIdentityVerificationRequest, WidgetConfiguration
      rpc :updateOrigins, UpdateOriginListRequest, WidgetConfiguration
      rpc :updateEnabled, UpdateEnabledRequest, WidgetConfiguration
    end

    Stub = Service.rpc_stub_class
  end
end
