# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: passkit_sdk/widget/widget.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file('passkit_sdk/widget/widget.proto', :syntax => :proto3) do
    add_message 'widget.WidgetConfiguration' do
      optional :id, :uint32, 1
      optional :key, :string, 2
      optional :secret, :string, 3
      optional :parentId, :string, 4
      optional :protocol, :enum, 5, 'widget.Protocol'
      optional :hasIdentityVerificationEnabled, :bool, 6
      optional :enabled, :bool, 7
      repeated :origins, :string, 8
    end
    add_message 'widget.WidgetKey' do
      optional :key, :string, 1
    end
    add_message 'widget.UpdateIdentityVerificationRequest' do
      optional :key, :string, 1
      optional :hasIdentityVerificationEnabled, :bool, 2
    end
    add_message 'widget.UpdateOriginListRequest' do
      optional :key, :string, 1
      repeated :origins, :string, 2
    end
    add_message 'widget.UpdateEnabledRequest' do
      optional :key, :string, 1
      optional :enabled, :bool, 2
    end
    add_enum 'widget.Protocol' do
      value :PARKING, 0
    end
  end
end

module PasskitSdk
  module Widget
    WidgetConfiguration = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('widget.WidgetConfiguration').msgclass
    WidgetKey = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('widget.WidgetKey').msgclass
    UpdateIdentityVerificationRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('widget.UpdateIdentityVerificationRequest').msgclass
    UpdateOriginListRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('widget.UpdateOriginListRequest').msgclass
    UpdateEnabledRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('widget.UpdateEnabledRequest').msgclass
    Protocol = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('widget.Protocol').enummodule
  end
end
