# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: passkit_sdk/member/a_rpc.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
require 'google/protobuf/empty_pb'
require 'passkit_sdk/common/common_objects_pb'
require 'passkit_sdk/common/message_pb'
require 'passkit_sdk/common/pagination_pb'
require 'passkit_sdk/common/filter_pb'
require 'passkit_sdk/member/member_events_pb'
require 'passkit_sdk/member/member_pb'
require 'passkit_sdk/member/program_pb'
require 'passkit_sdk/member/tier_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file('passkit_sdk/member/a_rpc.proto', :syntax => :proto3) do
  end
end

module PasskitSdk
  module Members
  end
end
