# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: passkit_sdk/single_use_coupons/a_rpc.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'
require 'google/api/annotations_pb'
require 'passkit_sdk/common/common_objects_pb'
require 'passkit_sdk/common/pagination_pb'
require 'passkit_sdk/common/filter_pb'
require 'passkit_sdk/common/reporting_pb'
require 'passkit_sdk/single_use_coupons/campaign_pb'
require 'passkit_sdk/single_use_coupons/offer_pb'
require 'passkit_sdk/single_use_coupons/coupon_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file('passkit_sdk/single_use_coupons/a_rpc.proto', :syntax => :proto3) do
  end
end

module PasskitSdk
  module SingleUseCoupons
  end
end
