# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: passkit_sdk/raw/a_rpc.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'
require 'google/api/annotations_pb'
require 'passkit_sdk/common/common_objects_pb'
require 'passkit_sdk/raw/project_pb'
require 'passkit_sdk/raw/pass_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file('passkit_sdk/raw/a_rpc.proto', :syntax => :proto3) do
  end
end

module PasskitSdk
  module Raw
  end
end
