# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: passkit_sdk/raw/pass.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'passkit_sdk/common/metrics_pb'
require 'passkit_sdk/common/pagination_pb'
require 'passkit_sdk/common/filter_pb'
require 'passkit_sdk/common/pass_pb'
require 'passkit_sdk/common/personal_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file('passkit_sdk/raw/pass.proto', :syntax => :proto3) do
    add_message 'raw.Pass' do
      optional :id, :string, 1
      optional :externalId, :string, 2
      optional :passProjectId, :string, 3
      optional :passTemplateId, :string, 4
      optional :personalDetails, :message, 5, 'io.Person'
      map :dynamicData, :string, :string, 6
      optional :optOut, :bool, 8
      optional :isVoided, :bool, 9
      optional :invalidateDate, :message, 10, 'google.protobuf.Timestamp'
      optional :expiryDate, :message, 11, 'google.protobuf.Timestamp'
      optional :passOptions, :message, 12, 'io.PassOptions'
      optional :passOverrides, :message, 13, 'io.PassOverrides'
      optional :passMetaData, :message, 14, 'io.Metadata'
      optional :created, :message, 15, 'google.protobuf.Timestamp'
      optional :updated, :message, 16, 'google.protobuf.Timestamp'
    end
    add_message 'raw.PassRecordByExternalIdRequest' do
      optional :passProjectId, :string, 1
      optional :externalId, :string, 2
    end
    add_message 'raw.ListPassesByPassProjectRequest' do
      optional :passProjectId, :string, 1
      optional :filters, :message, 2, 'io.Filters'
    end
    add_message 'raw.ListPassesByPassTemplateRequest' do
      optional :passProjectId, :string, 1
      optional :filters, :message, 2, 'io.Filters'
    end
  end
end

module PasskitSdk
  module Raw
    Pass = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('raw.Pass').msgclass
    PassRecordByExternalIdRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('raw.PassRecordByExternalIdRequest').msgclass
    ListPassesByPassProjectRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('raw.ListPassesByPassProjectRequest').msgclass
    ListPassesByPassTemplateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('raw.ListPassesByPassTemplateRequest').msgclass
  end
end
