# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: passkit_sdk/raw/project.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'passkit_sdk/common/distribution_pb'
require 'passkit_sdk/common/localization_pb'
require 'passkit_sdk/common/project_pb'
require 'passkit_sdk/common/billing_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file('passkit_sdk/raw/project.proto', :syntax => :proto3) do
    add_message 'raw.PassProject' do
      optional :id, :string, 1
      optional :name, :string, 2
      optional :localizedName, :message, 3, 'io.LocalizedString'
      repeated :status, :enum, 4, 'io.ProjectStatus'
      optional :quota, :message, 5, 'io.Quota'
      optional :passTypeIdentifier, :string, 6
      optional :distributionSettings, :message, 7, 'io.DistributionSettings'
      optional :created, :message, 8, 'google.protobuf.Timestamp'
      optional :updated, :message, 9, 'google.protobuf.Timestamp'
    end
    add_message 'raw.PassProjectCopyRequest' do
      optional :id, :string, 1
      optional :name, :string, 2
      repeated :status, :enum, 3, 'io.ProjectStatus'
      optional :passTypeIdentifier, :string, 4
    end
  end
end

module PasskitSdk
  module Raw
    PassProject = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('raw.PassProject').msgclass
    PassProjectCopyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('raw.PassProjectCopyRequest').msgclass
  end
end
