# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: passkit_sdk/flights/a_rpc.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
require 'google/protobuf/empty_pb'
require 'passkit_sdk/flights/boarding_pass_pb'
require 'passkit_sdk/flights/airport_pb'
require 'passkit_sdk/flights/flight_pb'
require 'passkit_sdk/flights/flight_designator_pb'
require 'passkit_sdk/flights/carrier_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file('passkit_sdk/flights/a_rpc.proto', :syntax => :proto3) do
  end
end

module PasskitSdk
  module Flights
  end
end
