# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: passkit_sdk/analytics/a_rpc.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
require 'passkit_sdk/common/reporting_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file('passkit_sdk/analytics/a_rpc.proto', :syntax => :proto3) do
  end
end

module PasskitSdk
  module Analytics
  end
end
